openapi: "3.0.2"
info:
  title: EasyQR API
  version: "1.0"
servers:
  - url: https://localhost:3000/api/v1
paths:
  /booking/{id}:
    $ref: "./Booking_request.yml#/booking_one"
  /booking/list:
    $ref: "./Booking_request.yml#/booking_list"
  /booking/create:
    $ref: "./Booking_request.yml#/booking_create"
components:
  schemas:
    User:
      $ref: "./User.yml"
    Booking:
      $ref: "./Booking.yml"
    City:
      $ref: "./City.yml"
    Rest:
      $ref: "./Rest.yml"
    Term:
      $ref: "./Term.yml"
    OrderStatus:
      $ref: "./OrderStatus.yml"
    OrderType:
      $ref: "./OrderType.yml"
